export const info_digital = [
  {
    name: "DIGITAL SKILLS",
    data: [
      "git",
      "doker",
      "postman",
      "clickup",
      "jira",
      "google-firbase",
      "google-maps",
      "windows",
      "MacOs",

      "Microsoft Viso",
      "Microsoft Office",
    ],
  },
  {
    name: "web",
    data: [
      "CSS/SASS",
      "HTML5",
      "BOOTSTRAP",
      "MomentJs",
      "ThreeJs",
      "GSAP3",
      "axios",
      "socket.io",
      "meteorJs",
      "webpack",
    ],
  },
  {
    name: "ReactJs",
    data: [
      "React Hooks",
      "Redux Tolkit Saga Thunk",
      "react-router",
      "formik",
      "reacti18n",
      "material-ui",
      "react-bootstrap",
      "react-query",
      "react-table",
      "react-select",
      "react-three/fiber",
      "react-three/drei",
      "react-three/postprocessing",
      "react-spring",
      "framer-motion",
      "theaterJs",
      "GraphQl",
      "react-apollo",
      "zustand",
      "react-meteor",
      "nextJs",
      "react-use",
      "uniswap",
    ],
  },

  {
    name: "React Native",
    data: [
      "react-navigation",
      "react-native-paper",
      "Native Modules",
      "Hermes",
      "Bluetooth",
      "react-native-reanimated",
    ],
  },
  {
    name: "Backend & Database",
    data: ["Laravel", "NodeJS/Express.js", "MySQL", "Microsoft SQL Servier"],
  },
  {
    name: "Programing Language",
    data: ["JavaScript/TypeScript", "PHP", "C#", "Java", "glsl"],
  },
  {
    name: "Familiar With",
    data: ["AdobeXd", "Adobe Photoshop & Illustrator", "Figma", "Blender"],
  },
];
