export const info_digital = [
  // {
  //   name: "ReactJs",
  //   data: [
  //     "React Hooks",

  //     "nextJs",
  //     // "react-router",
  //     // "formik",
  //     // "reacti18n",
  //     "material-ui",
  //     // "react-bootstrap",
  //     // "react-spring",
  //     "framer-motion",
  //     // "react-query",
  //     // "react-table",
  //     // "react-select",

  //     // "react-contexify",
  //     // "GraphQl",
  //     // "react-apollo",
  //     // "react-meteor",
  //     // "immer",
  //     // "react-use",
  //     // "uniswap",
  //   ],
  // },
  // {
  //   name: "DIGITAL SKILLS",
  //   data: [
  //     "git",
  //     "doker",
  //     "postman",
  //     "clickup",
  //     "jira",
  //     "google-firbase",
  //     "google-maps",
  //     "windows",
  //     "MacOs",

  //     "Microsoft Viso",
  //     "Microsoft Office",
  //   ],
  // },
  // {
  //   name: "web",
  //   data: [
  //     "CSS/SASS",
  //     "HTML5",
  //     "BOOTSTRAP",
  //     "MomentJs",
  //     "GSAP3",
  //     "tailwindcss",
  //     "axios",
  //     "socket.io",
  //     "meteorJs",
  //     "webpack",
  //   ],
  // },

  // {
  //   name: "web 3d development",
  //   data: [
  //     "ThreeJs",
  //     "@react-three/fiber",
  //     "@react-three/drei",
  //     "@react-three/gltfjsx",
  //     "@react-three/postprocessing",
  //     "@react-three/flex",
  //     "@react-three/cannon",
  //     "@react-three/a11y",
  //     "@react-spring/three",
  //     "@use-gesture/react",
  //     "framer-motion/three",
  //     "react-three-csg",
  //     "theaterJs",
  //     "Matterport",
  //     "maath",
  //     "leva",
  //     "three.meshline",
  //   ],
  // },

  // {
  //   name: "React Native",
  //   data: [
  //     "react-navigation",
  //     "react-native-paper",
  //     "Native Modules",
  //     "Hermes",
  //     "Bluetooth",
  //     "react-native-reanimated",
  //   ],
  // },
  {
    name: "ReactJs & NextJS",
    data: [
      { name: "ReactJs", experiance: "", bold: true, fontSize: "h4" },
      { name: "NextJS", experiance: "", bold: true, fontSize: "h4" },
      { name: "ReactNative", experiance: "", fontSize: "h5" },

      // { name: "Hooks", experiance: "", fontSize: "h5", bold: true },
      { name: "MUI", experiance: "", fontSize: "h5" },
      // { name: "bootstrap", experiance: "",fontSize:'h5' },
      { name: "SASS", experiance: "", bold: true, fontSize: "h5" },

      { name: "framer-motion", experiance: "", bold: true, fontSize: "h5" },
      // { name: "formik", experiance: "", fontSize: "h5" },
      // { name: "i18n", experiance: "", fontSize: "h5" },

      { name: "Redux ", experiance: "", bold: true, fontSize: "h5" },
      // { name: "contextAPI", experiance: "",fontSize:'h5' },
      { name: "zustand", experiance: "", bold: true, fontSize: "h5" },
      { name: "indexedDb ", experiance: "", fontSize: "h5" },

      { name: "webpack", experiance: "", bold: true, fontSize: "h5" },
      { name: "socket.io", experiance: "", fontSize: "h5" },
      { name: "GraphQl", experiance: "", fontSize: "h5" },
      { name: "firebase", experiance: "", fontSize: "h5" },
      { name: "meteorJs", experiance: "", fontSize: "h5" },
      // { name: "git", experiance: "", fontSize: "h5" },
      // { name: "postman", experiance: "", fontSize: "h5" },
      // { name: "ClickUp", experiance: "", fontSize: "h5", bold: true },
      { name: "gsap", experiance: "", fontSize: "h5" },
      // { name: "mo  mentJs", experiance: "" ,fontSize:'h5'},

      { name: "Threejs", experiance: "", bold: true, fontSize: "h4" },
      {
        name: "react-three/fiber/drei/rapier/gltfjsx",
        experiance: "",
        bold: true,
        fontSize: "h5",
      },
      { name: "blender", experiance: "", fontSize: "h5" },

      { name: "Matterport", experiance: "", fontSize: "h5" },
      { name: "git", experiance: "", fontSize: "h4", bold:true },
      { name: "MySql", experiance: "", fontSize: "h5" },
      { name: "Laravel", experiance: "", fontSize: "h5" },
      { name: "Nestjs", experiance: "", fontSize: "h5" },

      // { name: "@react-three/drei", experiance: "", fontSize: "h5" },
      // {
      //   name: "@react-three/RAPIER",
      //   experiance: "",
      //   fontSize: "h5",
      //   bold: true,
      // },
      // { name: "gltfjsx", experiance: "", bold: true, fontSize: "h5" },
    ],
  },

  // {
  //   name: "Backend & Database",
  //   data: [
  //     "Laravel",
  //     "NodeJS",
  //     "MySQL",
  //     // "Microsoft SQL Servier",
  //     // "MongoDb",
  //   ],
  // },
  // {
  //   name: "Programing Language",
  //   data: ["JavaScript/TypeScript", "glsl", "PHP", "C#"],
  // },
  // {
  //   name: "Familiar With",
  //   data: ["AdobeXd & Photoshop & Illustrator", "Figma", "Blender", "Office"],
  // },
];
