export const info_digital = [
  {
    name: "DIGITAL SKILLS",
    data: [
      "git",
      "doker",
      "postman",
      "clickup",
      "jira",
      "google-firbase",
      "google-maps",
      "windows",
      "MacOs",

      "Microsoft Viso",
      "Microsoft Office",
    ],
  },
  {
    name: "web",
    data: [
      "CSS/SASS",
      "HTML5",
      "BOOTSTRAP",
      "MomentJs",
      "GSAP3",
      "tailwindcss",
      "axios",
      "socket.io",
      "meteorJs",
      "webpack",
    ],
  },
  {
    name: "ReactJs",
    data: [
      "React Hooks",

      "nextJs",
      "react-router",
      "formik",
      "reacti18n",
      "material-ui",
      "react-bootstrap",
      "react-spring",
      "framer-motion",
      "react-query",
      "react-table",
      "react-select",

      "react-contexify",
      "GraphQl",
      "react-apollo",
      "react-meteor",
      "immer",
      "react-use",
      // "uniswap",
    ],
  },
  {
    name: "web 3d development",
    data: [
      "ThreeJs",
      "@react-three/fiber",
      "@react-three/drei",
      "@react-three/gltfjsx",
      "@react-three/postprocessing",
      "@react-three/flex",
      "@react-three/cannon",
      "@react-three/a11y",
      "@react-spring/three",
      "@use-gesture/react",
      "framer-motion/three",
      "react-three-csg",
      "theaterJs",
      "Matterport",
      "maath",
      "leva",
      "three.meshline",
    ],
  },
  {
    name: "state management",
    data: [
      "Redux Tolkit Saga Thunk",
      "zustand",
      "indexedDb dexie",
      "dexie-react-hooks",
      "@hookstate/core",
      "recoil",
      "xstate/react",
      "mobx-react",
      "Rematch",
      "jotai",
      "valtio",
    ],
  },

  {
    name: "React Native",
    data: [
      "react-navigation",
      "react-native-paper",
      "Native Modules",
      "Hermes",
      "Bluetooth",
      "react-native-reanimated",
    ],
  },
  {
    name: "Backend & Database",
    data: [
      "Laravel",
      "NodeJS/Express.js",
      "MySQL",
      "Microsoft SQL Servier",
      "MongoDb",
    ],
  },
  {
    name: "Programing Language",
    data: ["JavaScript/TypeScript", "PHP", "C#", "Java", "glsl"],
  },
  {
    name: "Familiar With",
    data: ["AdobeXd", "Adobe Photoshop & Illustrator", "Figma", "Blender"],
  },
];
